import { useMemo, useState } from 'react'
import { useLocation } from 'react-router-dom'
import {
  ArrowRight, BadgeDollarSign, BarChart3, CalendarDays, Camera, Check, ChevronDown, CircleDollarSign,
  ClipboardCheck, Clock3, Download, Eye, ImagePlus, MessageCircle, MoreHorizontal, Package, Pencil,
  Plus, Search, Sparkles, Star, Target, TrendingUp, UserCheck, Users, WalletCards, X
} from 'lucide-react'
import { AppShell } from '../../components/AppShell'
import { Avatar, Badge, Modal, PageHeader, SectionHeading, StatCard, Toast } from '../../components/ui'
import { appointments, clients, images } from '../../data/mock'

export function ProfessionalArea() {
  const path = useLocation().pathname
  let page = <ProfessionalHome />
  if (path.includes('/agenda')) page = <ProfessionalAgenda />
  else if (path.includes('/clientes')) page = <ProfessionalClients />
  else if (path.includes('/fichas')) page = <TechnicalRecords />
  else if (path.includes('/comissao') || path.includes('/desempenho')) page = <Performance />
  else if (path.includes('/servicos')) page = <ProfessionalServices />
  else if (path.includes('/perfil')) page = <ProfessionalProfile />
  return <AppShell role="profissional">{page}</AppShell>
}

function ProfessionalHome() {
  const [active,setActive]=useState(false); const [toast,setToast]=useState(false)
  return <div className="animate-fade-up"><Toast show={toast} message="Atendimento iniciado"/><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="text-sm text-stone-500">Domingo, 21 de junho</div><h1 className="font-display text-4xl font-semibold">Bom dia, Juliana.</h1><p className="muted mt-2">Sua agenda está com 82% de ocupação hoje.</p></div><button onClick={()=>{setActive(true);setToast(true);setTimeout(()=>setToast(false),2200)}} className="btn-primary"><Sparkles size={17}/>Iniciar próximo atendimento</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Atendimentos hoje" value="4" trend="1 finalizado • 3 próximos" icon={<CalendarDays size={20}/>}/><StatCard label="Faturamento estimado" value="R$ 2.360" trend="+18% vs. último domingo" icon={<CircleDollarSign size={20}/>}/><StatCard label="Comissão estimada" value="R$ 708" trend="30% sobre serviços" icon={<WalletCards size={20}/>} tone="dark"/><StatCard label="Meta mensal" value="74%" trend="R$ 18.420 de R$ 25.000" icon={<Target size={20}/>}/></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="surface p-5 sm:p-6"><SectionHeading title="Agenda de hoje" link="Ver agenda completa"/><div className="space-y-2">{appointments.map((a,i)=><div key={a.time} className={`grid grid-cols-[54px_1fr_auto] items-center gap-3 rounded-2xl border p-3 sm:grid-cols-[64px_1fr_auto_auto] ${i===2?'border-champagne/50 bg-champagne/[.05]':'border-black/[.05]'}`}><div className="text-center"><b className="block text-sm">{a.time}</b><span className="text-[9px] text-stone-400">{a.duration}</span></div><div className="flex min-w-0 items-center gap-3"><Avatar src={a.photo} name={a.client}/><div className="min-w-0"><div className="truncate text-xs font-bold">{a.client}</div><div className="mt-1 truncate text-[10px] text-stone-400">{a.service}</div></div></div><span className="hidden sm:block"><Status value={a.status}/></span><button className="grid h-9 w-9 place-items-center rounded-xl bg-warm"><MoreHorizontal size={16}/></button></div>)}</div></section>
      <div className="space-y-5"><section className="hair-gradient rounded-[26px] p-6 text-white"><div className="flex items-center justify-between"><div className="eyebrow">PRÓXIMA CLIENTE</div><Badge tone="green">Confirmada</Badge></div><div className="mt-5 flex items-center gap-4"><Avatar src={images.client1} name="Camila Ferreira" size="lg"/><div><h3 className="font-display text-2xl font-semibold">Camila Ferreira</h3><p className="text-[11px] text-white/45">14:30 • Aplicação Microlink</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-[11px]"><div className="rounded-xl bg-white/[.06] p-3"><span className="text-white/40">Último serviço</span><b className="mt-1 block">Avaliação • 12/06</b></div><div className="rounded-xl bg-white/[.06] p-3"><span className="text-white/40">Observação</span><b className="mt-1 block">Sensível na nuca</b></div></div><button onClick={()=>setActive(true)} className="btn-gold mt-5 w-full">Abrir ficha técnica <ArrowRight size={16}/></button></section>
      <section className="surface p-6"><SectionHeading title="Seu desempenho"/><div className="grid grid-cols-3 text-center"><div><div className="font-display text-2xl font-semibold">4,9</div><div className="mt-1 text-[9px] text-stone-400">Avaliação</div></div><div className="border-x border-black/[.06]"><div className="font-display text-2xl font-semibold">68%</div><div className="mt-1 text-[9px] text-stone-400">Recorrência</div></div><div><div className="font-display text-2xl font-semibold">#2</div><div className="mt-1 text-[9px] text-stone-400">Ranking</div></div></div></section></div></div>
    <TechnicalModal open={active} onClose={()=>setActive(false)}/>
  </div>
}

function Status({value}:{value:string}){const tone=value==='Confirmado'?'green':value==='Aguardando sinal'?'amber':value==='Em atendimento'?'gold':value==='Finalizado'?'neutral':'rose';return <Badge tone={tone}>{value}</Badge>}

function ProfessionalAgenda(){
  const [view,setView]=useState('Dia'); const [status,setStatus]=useState<Record<number,string>>({}); const [block,setBlock]=useState(false); const [toast,setToast]=useState(false)
  return <div className="animate-fade-up"><Toast show={toast} message="Agenda atualizada"/><PageHeader eyebrow="GESTÃO DE TEMPO" title="Agenda profissional" subtitle="Organize atendimentos, bloqueios e encaixes sem perder o ritmo do salão." action={<div className="flex gap-2"><button onClick={()=>setBlock(true)} className="btn-secondary"><X size={16}/>Bloquear horário</button><button className="btn-primary"><Plus size={16}/>Criar encaixe</button></div>}/>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-2xl bg-warm p-1">{['Dia','Semana','Mês'].map(v=><button key={v} onClick={()=>setView(v)} className={`rounded-xl px-5 py-2 text-xs font-bold ${view===v?'bg-white shadow-sm':'text-stone-400'}`}>{v}</button>)}</div><div className="flex items-center gap-3"><button className="btn-secondary !min-h-10 !px-3">‹</button><div className="text-sm font-bold">21 de junho de 2026</div><button className="btn-secondary !min-h-10 !px-3">›</button></div></div>
    <section className="surface overflow-hidden"><div className="grid grid-cols-[64px_1fr] border-b border-black/[.05] bg-warm/60 p-4 text-[10px] font-bold uppercase tracking-wider text-stone-400"><span>Hora</span><span>Atendimento</span></div>{appointments.map((a,i)=>{const s=status[i]||a.status;return <div key={a.time} className="grid grid-cols-[64px_1fr] border-b border-black/[.05] last:border-0"><div className="border-r border-black/[.05] p-4 text-xs font-bold">{a.time}</div><div className="m-2 flex flex-col gap-3 rounded-2xl bg-warm/60 p-4 sm:flex-row sm:items-center"><Avatar src={a.photo} name={a.client}/><div className="min-w-0 flex-1"><div className="text-xs font-bold">{a.client}</div><div className="mt-1 text-[10px] text-stone-400">{a.service} • {a.duration} • {a.value}</div></div><Status value={s}/><select value={s} onChange={e=>{setStatus({...status,[i]:e.target.value});setToast(true);setTimeout(()=>setToast(false),1800)}} className="rounded-xl border border-black/[.07] bg-white px-3 py-2 text-[10px] font-semibold outline-none"><option>Confirmado</option><option>Aguardando sinal</option><option>Em atendimento</option><option>Finalizado</option><option>Cancelado</option><option>Faltou</option><option>Reagendado</option></select></div></div>})}</section>
    <Modal open={block} onClose={()=>setBlock(false)} title="Bloquear horário"><div className="grid grid-cols-2 gap-4"><label><span className="mb-2 block text-xs font-bold">Data</span><input type="date" defaultValue="2026-06-22" className="field"/></label><label><span className="mb-2 block text-xs font-bold">Início</span><input type="time" defaultValue="12:00" className="field"/></label></div><label className="mt-4 block"><span className="mb-2 block text-xs font-bold">Motivo</span><select className="field"><option>Intervalo</option><option>Compromisso pessoal</option><option>Treinamento</option><option>Outro</option></select></label><button onClick={()=>{setBlock(false);setToast(true);setTimeout(()=>setToast(false),1800)}} className="btn-primary mt-5 w-full">Confirmar bloqueio</button></Modal>
  </div>
}

function ProfessionalClients(){
  const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const filtered=clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase()))
  return <div className="animate-fade-up"><PageHeader eyebrow="RELACIONAMENTO" title="Suas clientes" subtitle="Informações importantes para um atendimento atento e consistente." action={<div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} className="field pl-11 sm:w-72" placeholder="Buscar cliente"/></div>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><button key={c.name} onClick={()=>setOpen(true)} className="surface p-5 text-left transition hover:-translate-y-1"><div className="flex items-center gap-3"><Avatar src={c.photo} name={c.name} size="lg"/><div className="min-w-0 flex-1"><h3 className="truncate font-display text-2xl font-semibold">{c.name}</h3><p className="text-[10px] text-stone-400">{c.phone}</p></div><Status value={c.tag==='VIP'?'Confirmado':c.tag}/></div><div className="mt-5 grid grid-cols-3 rounded-2xl bg-warm p-4 text-center"><div><b className="text-xs">{c.last}</b><span className="mt-1 block text-[8px] text-stone-400">Última visita</span></div><div className="border-x border-black/[.06]"><b className="text-xs">{c.ticket}</b><span className="mt-1 block text-[8px] text-stone-400">Ticket médio</span></div><div><b className="text-xs">{c.points}</b><span className="mt-1 block text-[8px] text-stone-400">Pontos</span></div></div><div className="mt-4 flex items-center justify-between text-[10px] text-stone-400"><span>Próxima: {c.next}</span><span className="font-bold text-champagne">Ver ficha →</span></div></button>)}</div><TechnicalModal open={open} onClose={()=>setOpen(false)}/>
  </div>
}

function TechnicalRecords(){const [open,setOpen]=useState(false);return <div className="animate-fade-up"><PageHeader eyebrow="HISTÓRICO TÉCNICO" title="Fichas técnicas" subtitle="Registre cada detalhe para preservar o resultado e a saúde dos fios." action={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={16}/>Nova ficha</button>}/><section className="surface overflow-hidden"><div className="grid grid-cols-[1fr_auto] gap-4 border-b border-black/[.05] p-5 sm:grid-cols-[1fr_170px_160px_150px_auto]"><span className="text-[10px] font-bold uppercase tracking-wider text-stone-400">Cliente</span><span className="hidden text-[10px] font-bold uppercase tracking-wider text-stone-400 sm:block">Método</span><span className="hidden text-[10px] font-bold uppercase tracking-wider text-stone-400 sm:block">Última aplicação</span><span className="hidden text-[10px] font-bold uppercase tracking-wider text-stone-400 sm:block">Retorno</span><span/></div>{clients.map((c,i)=><div key={c.name} className="grid grid-cols-[1fr_auto] items-center gap-4 border-b border-black/[.05] p-5 last:border-0 sm:grid-cols-[1fr_170px_160px_150px_auto]"><div className="flex items-center gap-3"><Avatar src={c.photo} name={c.name}/><div><b className="text-xs">{c.name}</b><span className="mt-1 block text-[9px] text-stone-400">Ficha CS-{2600+i}</span></div></div><span className="hidden text-xs sm:block">{i%2?'Microlink':'Fita Adesiva'}</span><span className="hidden text-xs sm:block">{c.last}</span><span className="hidden sm:block"><Badge tone={c.next==='—'?'amber':'green'}>{c.next}</Badge></span><button onClick={()=>setOpen(true)} className="grid h-9 w-9 place-items-center rounded-xl bg-warm"><Eye size={15}/></button></div>)}</section><TechnicalModal open={open} onClose={()=>setOpen(false)}/></div>}

function TechnicalModal({open,onClose}:{open:boolean;onClose:()=>void}){
  const [saved,setSaved]=useState(false)
  return <Modal open={open} onClose={onClose} title="Ficha técnica — Camila"><div className="flex items-center gap-3 rounded-2xl bg-warm p-4"><Avatar src={images.client1} name="Camila Ferreira"/><div><div className="text-xs font-bold">Camila Ferreira</div><div className="text-[10px] text-stone-400">Aplicação Microlink • 21/06/2026</div></div><Badge tone="gold">Em atendimento</Badge></div><div className="mt-5 grid grid-cols-2 gap-3"><Field label="Método" value="Microlink Premium"/><Field label="Quantidade" value="120 mechas"/><Field label="Peso" value="140g"/><Field label="Comprimento" value="60 cm"/><Field label="Cor / tonalidade" value="Castanho 4/6"/><Field label="Lote" value="CS2605"/></div><label className="mt-4 block"><span className="mb-2 block text-xs font-bold">Produtos utilizados</span><input className="field" defaultValue="Protetor térmico Carol Sol, sérum reconstrutor"/></label><label className="mt-4 block"><span className="mb-2 block text-xs font-bold">Cuidados e observações</span><textarea className="field min-h-24 py-3" defaultValue="Cliente com sensibilidade na nuca. Evitar tensão nas duas primeiras fileiras."/></label><div className="mt-4 grid grid-cols-3 gap-2">{['Antes','Durante','Depois'].map(x=><label key={x} className="grid aspect-square cursor-pointer place-items-center rounded-2xl border border-dashed border-champagne/50 bg-warm text-center"><div><Camera className="mx-auto text-champagne" size={19}/><span className="mt-1 block text-[9px] font-bold">{x}</span></div><input type="file" className="hidden" accept="image/*"/></label>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setSaved(true)} className="btn-secondary"><Download size={16}/>Gerar resumo</button><button onClick={()=>{setSaved(true);setTimeout(onClose,900)}} className="btn-primary"><Check size={16}/>Salvar ficha</button></div>{saved&&<div className="mt-3 rounded-xl bg-emerald-50 p-3 text-center text-[11px] font-bold text-emerald-700">Ficha salva e resumo preparado para a cliente.</div>}</Modal>
}
function Field({label,value}:{label:string;value:string}){return <label><span className="mb-2 block text-[10px] font-bold text-stone-500">{label}</span><input className="field !min-h-10 !text-xs" defaultValue={value}/></label>}

function Performance(){
  return <div className="animate-fade-up"><PageHeader eyebrow="RESULTADOS" title="Comissão e desempenho" subtitle="Acompanhe seus números e identifique as melhores oportunidades do mês." action={<button className="btn-secondary"><Download size={16}/>Exportar extrato</button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Comissão em junho" value="R$ 5.526" trend="+12,4% vs. maio" icon={<BadgeDollarSign size={19}/>} tone="dark"/><StatCard label="Ticket médio" value="R$ 768" trend="+R$ 82 neste mês" icon={<TrendingUp size={19}/>}/><StatCard label="Produtos vendidos" value="R$ 2.480" trend="18 kits Home Care" icon={<Package size={19}/>}/><StatCard label="Clientes recorrentes" value="68%" trend="Meta: 72%" icon={<UserCheck size={19}/>}/></div><div className="mt-6 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="surface p-6"><SectionHeading title="Evolução mensal" link="Últimos 6 meses"/><div className="mt-8 flex h-64 items-end gap-3 border-b border-black/[.06]">{[['Jan',46],['Fev',58],['Mar',52],['Abr',70],['Mai',76],['Jun',88]].map(([m,h])=><div key={m} className="flex flex-1 flex-col items-center gap-2"><div className="relative flex w-full items-end justify-center" style={{height:'210px'}}><div className="w-full max-w-12 rounded-t-xl bg-gradient-to-t from-[#9e762e] to-[#dec17e]" style={{height:`${h}%`}}/><span className="absolute -top-5 text-[9px] font-bold">{h}%</span></div><span className="text-[9px] text-stone-400">{m}</span></div>)}</div></section><section className="surface p-6"><SectionHeading title="Meta do mês"/><div className="mx-auto mt-6 grid h-44 w-44 place-items-center rounded-full progress-ring"><div className="grid h-32 w-32 place-items-center rounded-full bg-white text-center"><div><b className="font-display text-4xl">74%</b><span className="block text-[9px] text-stone-400">R$ 18.420 / R$ 25.000</span></div></div></div><div className="mt-6 flex justify-between rounded-2xl bg-warm p-4 text-xs"><span className="text-stone-500">Faltam</span><b>R$ 6.580</b></div></section></div></div>
}

function ProfessionalServices(){return <div className="animate-fade-up"><PageHeader eyebrow="PORTFÓLIO" title="Seus serviços" subtitle="Procedimentos habilitados, duração, comissão e disponibilidade."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[['Fita Adesiva','3h30','30%','Ativo'],['Microlink','4h','30%','Ativo'],['Manutenção','2h30','35%','Ativo'],['Avaliação','45min','40%','Ativo'],['Remoção segura','1h30','30%','Ativo'],['Queratina','5h','—','Em treinamento']].map(x=><div key={x[0]} className="surface p-6"><div className="flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-warm text-champagne"><Sparkles size={19}/></span><Badge tone={x[3]==='Ativo'?'green':'amber'}>{x[3]}</Badge></div><h3 className="mt-4 font-display text-3xl font-semibold">{x[0]}</h3><div className="mt-5 grid grid-cols-2 rounded-2xl bg-warm p-4 text-xs"><span><span className="block text-[9px] text-stone-400">Duração</span><b>{x[1]}</b></span><span><span className="block text-[9px] text-stone-400">Comissão</span><b>{x[2]}</b></span></div></div>)}</div></div>}
function ProfessionalProfile(){return <div className="animate-fade-up"><PageHeader eyebrow="PERFIL PROFISSIONAL" title="Juliana Almeida" subtitle="Especialista em extensões • Unidade Jardins" action={<button className="btn-secondary"><Pencil size={16}/>Editar perfil</button>}/><div className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="surface p-7 text-center"><Avatar src={images.stylist2} name="Juliana Almeida" size="lg"/><h2 className="mt-4 font-display text-3xl font-semibold">Juliana Almeida</h2><p className="text-xs text-stone-400">Profissional sênior desde 2022</p><div className="mt-5 flex justify-center gap-1 text-champagne"><Star fill="currentColor" size={16}/><b className="text-xs text-ink">4,9</b><span className="text-[10px] text-stone-400">(284 avaliações)</span></div></div><div className="surface p-6"><SectionHeading title="Preferências de trabalho"/><div className="grid gap-4 sm:grid-cols-2"><Info label="Unidade padrão" value="Carol Sol Jardins"/><Info label="Jornada" value="Terça a sábado • 09h–19h"/><Info label="Comissão base" value="30% em serviços"/><Info label="Especialidades" value="Fita Adesiva, Microlink"/></div></div></div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-warm p-4"><span className="text-[9px] font-bold uppercase tracking-wider text-stone-400">{label}</span><b className="mt-2 block text-xs">{value}</b></div>}
