import { FormEvent, useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, Phone, ShieldCheck, Sparkles } from 'lucide-react'
import { images } from '../data/mock'
import { Logo } from '../components/ui'

const slides = [
  { eyebrow: 'MEGA HAIR PREMIUM', title: 'Transforme seu visual.', text: 'Resultados naturais, profissionais especialistas e uma jornada feita para você.', image: images.hero },
  { eyebrow: 'DIAGNÓSTICO PERSONALIZADO', title: 'Encontre o método ideal.', text: 'Conte seu objetivo, envie fotos e receba recomendações sob medida.', image: images.brunette },
  { eyebrow: 'CUIDADO CONTÍNUO', title: 'Agende e acompanhe.', text: 'Manutenção no tempo certo, histórico técnico, pontos e benefícios em um só lugar.', image: images.salon }
]

export function IntroPage() {
  const [splash, setSplash] = useState(true); const [slide, setSlide] = useState(0); const navigate = useNavigate()
  useEffect(() => { const id = setTimeout(() => setSplash(false), 1200); return () => clearTimeout(id) }, [])
  if (splash) return <div className="hair-gradient fixed inset-0 grid place-items-center"><div className="animate-fade-up text-center"><div className="mx-auto mb-5 grid h-24 w-24 place-items-center rounded-full border border-champagne/30 font-display text-6xl italic text-champagne">L</div><div className="font-display text-3xl tracking-[.2em] text-white">LUXE HAIR</div><div className="mt-2 text-[9px] font-semibold tracking-[.4em] text-white/45">MEGA HAIR PREMIUM</div></div></div>
  const current = slides[slide]
  return <div className="min-h-screen bg-cream p-3 sm:p-5"><div className="mx-auto grid min-h-[calc(100vh-24px)] max-w-[1380px] overflow-hidden rounded-[32px] bg-white shadow-luxe sm:min-h-[calc(100vh-40px)] lg:grid-cols-[1.12fr_.88fr]">
    <div className="relative min-h-[52vh] overflow-hidden lg:min-h-full"><img src={current.image} alt="Cabelo longo e saudável" className="absolute inset-0 h-full w-full object-cover transition duration-700" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/5 to-black/10" /><div className="absolute left-5 top-5"><Logo light /></div><div className="absolute bottom-0 p-7 text-white sm:p-12 lg:p-16"><div className="eyebrow mb-4">{current.eyebrow}</div><h1 className="max-w-xl font-display text-5xl font-semibold leading-[.9] sm:text-6xl lg:text-7xl">{current.title}</h1><p className="mt-5 max-w-md text-sm leading-relaxed text-white/70 sm:text-base">{current.text}</p></div></div>
    <div className="flex flex-col justify-between p-7 sm:p-12 lg:p-16"><div className="flex items-center justify-between"><span className="text-xs font-bold text-stone-400">{String(slide + 1).padStart(2, '0')} / 03</span><button onClick={() => navigate('/entrar')} className="text-xs font-bold text-stone-500">Pular</button></div><div className="my-10"><div className="mb-8 flex gap-2">{slides.map((_, i) => <button key={i} aria-label={`Tela ${i + 1}`} onClick={() => setSlide(i)} className={`h-1.5 rounded-full transition-all ${i === slide ? 'w-12 bg-champagne' : 'w-5 bg-stone-200'}`} />)}</div><div className="surface p-5"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-warm text-champagne"><ShieldCheck /></div><div><div className="text-sm font-bold">Sua beleza, seus dados</div><p className="mt-1 text-xs leading-relaxed text-stone-500">Experiência segura, transparente e com consentimento LGPD em cada etapa.</p></div></div></div></div><div className="flex gap-3">{slide > 0 && <button onClick={() => setSlide(slide - 1)} className="btn-secondary !px-4"><ArrowLeft size={18} /></button>}<button onClick={() => slide < 2 ? setSlide(slide + 1) : navigate('/entrar')} className="btn-primary flex-1">{slide < 2 ? 'Continuar' : 'Começar agora'}<ArrowRight size={18} /></button></div></div>
  </div></div>
}

export function AuthPage() {
  const navigate = useNavigate(); const location = useLocation(); const [showPassword, setShowPassword] = useState(false); const [role, setRole] = useState<'cliente' | 'profissional' | 'admin'>('cliente'); const [accepted, setAccepted] = useState(true)
  const mode = location.pathname.includes('cadastro') ? 'cadastro' : location.pathname.includes('recuperar') ? 'recuperar' : 'entrar'
  const enter = (e: FormEvent) => { e.preventDefault(); navigate(role === 'cliente' ? '/cliente/inicio' : role === 'profissional' ? '/profissional/hoje' : '/admin/dashboard') }
  return <div className="min-h-screen bg-cream p-3 sm:p-5"><div className="mx-auto grid min-h-[calc(100vh-24px)] max-w-[1380px] overflow-hidden rounded-[32px] bg-white shadow-luxe lg:grid-cols-2">
    <div className="relative hidden overflow-hidden lg:block"><img src={images.blonde} alt="Transformação Luxe Hair" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-black/20" /><div className="absolute left-10 top-10"><Logo light /></div><div className="absolute bottom-14 left-14 right-14 text-white"><div className="eyebrow mb-4">BELEZA QUE TRANSFORMA</div><h1 className="max-w-lg font-display text-6xl font-semibold leading-[.9]">Confiança que permanece.</h1><p className="mt-5 max-w-md text-sm leading-relaxed text-white/65">Tecnologia e cuidado especializado para acompanhar cada fase da sua transformação.</p></div></div>
    <div className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><button onClick={() => navigate('/')} className="mb-9 flex items-center gap-2 text-xs font-bold text-stone-400"><ArrowLeft size={15} />Voltar</button><div className="mb-8 lg:hidden"><Logo /></div><div className="eyebrow mb-3">BEM-VINDA À LUXE</div><h1 className="font-display text-4xl font-semibold sm:text-5xl">{mode === 'cadastro' ? 'Crie sua conta' : mode === 'recuperar' ? 'Recupere seu acesso' : 'Sua jornada continua'}</h1><p className="muted mt-3">{mode === 'recuperar' ? 'Enviaremos um link seguro para redefinir sua senha.' : 'Acesse com e-mail, telefone ou explore a demonstração.'}</p>
      {mode !== 'recuperar' && <div className="mt-7 grid grid-cols-3 rounded-2xl bg-warm p-1">{(['cliente', 'profissional', 'admin'] as const).map(r => <button key={r} onClick={() => setRole(r)} className={`rounded-xl px-2 py-2.5 text-[11px] font-bold capitalize transition ${role === r ? 'bg-white text-ink shadow-sm' : 'text-stone-400'}`}>{r}</button>)}</div>}
      <form onSubmit={enter} className="mt-7 space-y-4">
        {mode === 'cadastro' && <label className="block"><span className="mb-2 block text-xs font-bold">Nome completo</span><div className="relative"><Sparkles className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={17} /><input className="field pl-11" placeholder="Como podemos te chamar?" required /></div></label>}
        <label className="block"><span className="mb-2 block text-xs font-bold">{mode === 'cadastro' ? 'E-mail ou telefone' : 'E-mail ou telefone'}</span><div className="relative"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={17} /><input className="field pl-11" type="text" defaultValue={mode === 'entrar' ? role === 'admin' ? 'admin@luxehair.com.br' : role === 'profissional' ? '(11) 99932-4430' : 'juliana@email.com' : ''} placeholder="seu@email.com" required /></div></label>
        {mode !== 'recuperar' && <label className="block"><span className="mb-2 block text-xs font-bold">Senha</span><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={17} /><input className="field px-11" type={showPassword ? 'text' : 'password'} defaultValue="luxehair" required /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-4 top-1/2 -translate-y-1/2 text-stone-400">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>}
        {mode === 'cadastro' && <label className="flex items-start gap-3 text-[11px] leading-relaxed text-stone-500"><button type="button" onClick={() => setAccepted(!accepted)} className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-md ${accepted ? 'bg-ink text-white' : 'border border-black/15'}`}>{accepted && <Check size={13} />}</button><span>Li e aceito os Termos de Uso, Política de Privacidade e o tratamento dos meus dados conforme a LGPD.</span></label>}
        <button className="btn-primary w-full" disabled={mode === 'cadastro' && !accepted}>{mode === 'recuperar' ? 'Enviar link seguro' : mode === 'cadastro' ? 'Criar minha conta' : `Entrar como ${role}`}<ArrowRight size={17} /></button>
      </form>
      <div className="mt-5 text-center text-xs text-stone-500">{mode === 'entrar' ? <>Ainda não tem conta? <button onClick={() => navigate('/cadastro')} className="font-bold text-champagne">Cadastre-se</button><button onClick={() => navigate('/recuperar')} className="mt-3 block w-full font-semibold text-stone-400">Esqueci minha senha</button></> : <button onClick={() => navigate('/entrar')} className="font-bold text-champagne">Voltar para o login</button>}</div>
      <div className="mt-8 flex items-center justify-center gap-4 text-[10px] text-stone-400"><span className="flex items-center gap-1"><ShieldCheck size={13} />Dados protegidos</span><span className="flex items-center gap-1"><Phone size={13} />Suporte humanizado</span></div>
    </div></div>
  </div></div>
}
